### ISSUE TITLE
It doesn't work!

### ISSUE THREAD

**Issue by MCPEPIG** [PurePlugins/GamemodeInvSave#1]
It doesn't work! Is it even finished? :tongue:

**Comment by 64FF00** [comment]
@MCPEPIG It's now working :D

**Comment by MCPEPIG** [comment]
Cool!

**Comment by MCPEPIG** [comment]
Still doesnt work... It wont save the inventory :(

**Comment by 64FF00** [comment]
@MCPEPIG It works... I've already tested it!

**Comment by 64FF00** [comment]
Get the latest release and try again.

**Comment by MCPEPIG** [comment]
Nope still wont work

**Comment by 64FF00** [comment]
https://github.com/PurePlugins/GamemodeInvSave/commit/6c00c724f741711a8271cc1114a771607a27092b

**Comment by MCPEPIG** [comment]
Um ok

**Comment by 64FF00** [comment]
@MCPEPIG Could you pls check if it's fixed or not?

**Comment by MCPEPIG** [comment]
Works!!! But i found a bug...

**Comment by 64FF00** [comment]
@MCPEPIG What is it?

**Comment by MCPEPIG** [comment]
When i had 2 stacks of dirt then went in creative and back to survival, I lost 1 stack. I think it is like if you  have more than 1 stack of something, you'll loose the others and can only keep 1 stack of an item

**Comment by 64FF00** [comment]
@MCPEPIG Thanks a lot, gonna take a look at it!

**Comment by MCPEPIG** [comment]
Ok

**Comment by 64FF00** [comment]
91bf63232428bc8defe4fad4dad1b769f7c9c415

**Comment by MCPEPIG** [comment]
K

**Comment by MCPEPIG** [comment]
Works but when i had one and a half stack of dirt, then went to creative and back to suvival, i got one extra dirt

**Comment by MCPEPIG** [comment]
Looking for more bugs

**Comment by MCPEPIG** [comment]
Found another...

**Comment by MCPEPIG** [comment]
When i gave myself ink sac and red dye, then went to creative and back to survival, i got 64+64+34 red dye and ink sac

**Comment by MCPEPIG** [comment]
Also when i had a diamond sword in my inventory, and went into creative then survival, it gave me like 19 more of them and gave me more red dye and ink sac. Has something to do with damage value...

**Comment by MCPEPIG** [comment]
I also keep getting 1 extra dirt everytime still. The only thing that doesnt duplicate is the bowl i have (not bow!)

**Comment by MCPEPIG** [comment]
When i wear armor and go to creative then go back to survival, its no longer in armor slots... Instead, its in my inventory!

**Comment by 64FF00** [comment]
@MCPEPIG One extra dirt? Nope, can't seem to reproduce that issue.

**Comment by 64FF00** [comment]
@MCPEPIG About the armors... Need to fix it!

**Comment by MCPEPIG** [comment]
-,-

**Comment by 64FF00** [comment]
@MCPEPIG IT WORKSSSSS

**Comment by MCPEPIG** [comment]
I know, but I found a strange bug, when I wore a diamond helmet and went into creative then back to survival, i get another one. I tested it with chain helmet and was fine.

**Comment by 64FF00** [comment]
@MCPEPIG Ok then, I'll try to fix it in the next update.

**Comment by MCPEPIG** [comment]
Btw I had two diamind helmets before I went to creative (I wore one) That might be it
